# Generated by Django 2.2.5 on 2019-11-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(help_text='Please use the following format: YYYY-MM-DD')),
                ('citizenshipNumber', models.CharField(help_text='Enter your 10 digit citizenship Number', max_length=10)),
                ('street', models.CharField(default='', max_length=30)),
                ('suburb', models.CharField(default='', max_length=30)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('QLD', 'Queensland')], default='Select State', max_length=20)),
                ('pincode', models.IntegerField(default='')),
                ('mobileNumber', models.CharField(max_length=10)),
                ('drivingLicenseNo', models.CharField(blank=True, max_length=10)),
                ('passportNo', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='Unspecified', help_text='Select Gender', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
