# Generated by Django 2.2.5 on 2019-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='evidence',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='drivingLicenseNo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='passportNo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
