# Generated by Django 2.2.5 on 2019-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='citizenshipNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobileNumber',
            field=models.CharField(max_length=10),
        ),
    ]
