# Generated by Django 2.2.5 on 2019-11-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
