# Generated by Django 2.2.5 on 2019-11-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatepreference',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='partypreference',
            name='party',
        ),
        migrations.AddField(
            model_name='candidatepreference',
            name='candidate_surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partypreference',
            name='party_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
